title: FE Notes
description: 프론트엔드 개발 정리
baseurl: ""           # 사용자 페이지면 빈 값 유지
url: "https://hwayoung.github.io"
theme: null
markdown: kramdown
permalink: /:categories/:title/
collections:
  notes:
    output: true
defaults:
  - scope: { path: "", type: "notes" }
    values: { layout: default }
